CRM/Activityreport/Data.php

PR contains:
HW-117 - "Completed" Activity Status Total does not match with Find Activities fixing
HW-119 - Total number of activities mismatch fixing
HW-125 - Database field names changing

HW-94 subtasks

---

CRM/Activityreport/Upgrader.php
CRM/Activityreport/Upgrader/Base.php
activityreport.civix.php

Creating "Activity Report" link under Reports menu.

HR-130 - Creating Activity Report link under Reports menu.

---

README.md
info.xml

Adding README.md and changing info.xml.

HW-129 - Adding README.md file and changing info.xml.

---

CRM/Activityreport/Data.php

- Adding additional method for customizing Activity values.
- Adding 'campaign_id' field customization to get Campaign's title instead of ID.

HW-135 - Campaigns label

---

CRM/Activityreport/Data.php
templates/CRM/Activityreport/Page/ActivityReport.tpl

- Changing 'Activity Date' to show only year-month-day.
- Adding additional field 'Activity Date Time' containing full date and time.

HW-136 - Activity Date filter

---

CRM/Activityreport/Data.php
api/v3/ActivityReport.php
templates/CRM/Activityreport/Page/ActivityReport.tpl

- Handling multivalues combinations (splitting between API calls).
- Removing ActivityContact chaining.
- Removing some Activity basic and custom fields.
- Removing field labels from data.
- Adding CRM caching.

HW-275: v1 optimisations

---

CRM/Activityreport/Data.php
templates/CRM/Activityreport/Page/ActivityReport.tpl

V2 optimisations include:
- Excluding Activities with 'is_test' other than '0' and excluding 'RichTextEditor' custom fields.
- Removing debug messages.
- Moving Activity data loading code into separate function.
- Loading Activities by date when Activities number is greater than 5000.
- Implementing frontend date filter.
- Adding frontend CRM messages.
- Removing data caching on backend.

HW-275: v2 optimisations

---

CRM/Activityreport/Data.php
CRM/Activityreport/Page/ActivityReport.php
api/v3/ActivityReport.php
templates/CRM/Activityreport/Page/ActivityReport.tpl

Changes regarding Madura's feedback:
- Removing 'Original Activity ID' and 'Activity is a test' fields.
- Changing default date limit to 30 days instead of 1 month.

HW-275: v2 optimisations changes

---

CRM/Activityreport/Data.php
CRM/Activityreport/Page/ActivityReport.php
api/v3/ActivityReport.php
templates/CRM/Activityreport/Page/ActivityReport.tpl

- Implementing two datepicker input fields to filter Activities by date range instead of a single year/month pair.
- Changing info message copy.

HW-275: v2 optimisations (two datepicker fields)

---

js/pivottable/export_renderers.js

Updating export_renderers.js with additional code needed to create downloadable TSV / CSV pivot reports.

HW-339: Add extra functionality to compucorp pivot table repo

---

activityreport.php
js/PivotReport.Dates.js
js/PivotReport.PivotTable.js

Some date manipulation functions were added to PivotTable class.  These functions can be refactored into a new class.
Date manipulation functions were part of the PivotTable class.
Created a new Dates class to hold all date manipulation functions.

GS-56: Refactor Date Manipulation Methods Into New Class

---

css/style.css

Updating CSS to fix columns issues.
Before:
After fixing:

GS-69: Columns style issue

---

CRM/Activityreport/Entity.php
CRM/PivotCache/GroupCase.php
CRM/PivotReport/AbstractData.php
CRM/PivotReport/DataCase.php
templates/CRM/Activityreport/Page/CaseReport.tpl
xml/Menu/activityreport.xml

Adding Case entity support to Pivot Report extension.

GS-72: Case entity and caching

---

CRM/PivotReport/AbstractData.php
CRM/PivotReport/DataActivity.php
CRM/PivotReport/DataCase.php
CRM/PivotReport/DataContribution.php
CRM/PivotReport/DataMembership.php
CRM/PivotReport/DataProspect.php

- Adding "Pledge Financial Type" field to the report.
- Refactoring getOptionValues() method to handle entity optional value and moving the method to abstract class.
- Enabling text custom fields for Prospect entity report.

GS-75: Fields missing in prospect axes pool

---

CRM/PivotData/DataCase.php
CRM/PivotData/DataContribution.php
CRM/PivotData/DataMembership.php

- Adding 'Membership Name' and 'Relationship Name' fields to Membership report.
- Including text custom fields into all reports except Activity.

GS-74: Fields missing in axes pool

---

CRM/PivotReport/Upgrader.php

As reported by Madura - currently the scheduled job doesn't get disabled / uninstalled when disabling / uninstalling the extension. Also each installation of the extension causes creating a schedule job duplicate. So after few reinstallations we end up having few scheduled jobs duplicates.
Changes made:
- Creating a new upgrader function to remove scheduled job duplicates.
- Updating Upgrader class to disable / enable scheduled job when disabling / enabling the extension.
- Updating Upgrader class to remove scheduled job when uninstalling the extension.

GS-57: Scheduled job uninstallation issue

---

CRM/PivotData/DataCase.php

Adding 'Case Type' (case_type_id) field displaying Case Type label on Case pivot report.

GS-74: Adding case type field to case report

---

pivotreport.php

Adding Admin Pivot Report permission into hook_civicrm_permission implementation.

GS-91: Adding Admin Pivot Report permission

---

CRM/PivotData/AbstractData.php
CRM/PivotData/DataActivity.php
CRM/PivotReport/Entity.php
api/v3/PivotReport.php

- Implementing components validation for supported Pivot Report entities.
- Fixing 'index' parameter format (caused Activities skipping if there were more than 1000 Activities with the same date).
- Setting custom limits for Activity entity.
- Refactoring caching methods.

HW-433: Cache building error message and time out

---

js/FileSaver.js
js/PivotReport.Export.js
pivotreport.php

There was an issue causing error when trying to export Pivot Report into TSV/CSV file. It was probably because of browsers limitation.
I've used FileSaver.js class (https://github.com/eligrey/FileSaver.js) which allows to save large files generated by web browsers.

HW-433: Pivot Report TSV /CSV export issue

---

CRM/PivotData/AbstractData.php

Updating Pivot Report cache rebuilt time on rebuild cache scheduled job

HW-433: Updating Pivot Report cache rebuilt time on rebuild cache scheduled job

---

CRM/PivotData/DataActivity.php

Setting ROWS_RETURN_LIMIT to 1000 for Activity entity.

HW-433: Changing ROWS_RETURN_LIMIT for Activity report

---

CRM/PivotData/AbstractData.php

Setting 'is_active' to 1 for cache built with rebuildcache API action.

HW-433: Activate the cache after rebuildcache action is complete

---

CRM/PivotData/AbstractData.php

Setting empty value if Option Value doesn't exist.

HW-433: Setting empty value if Option Value doesn't exist.

---

CRM/PivotCache/AbstractGroup.php
CRM/PivotCache/PivotReportChunkStatus.php
CRM/PivotData/AbstractData.php
CRM/PivotData/DataCase.php
CRM/PivotReport/BAO/PivotReportCache.php
CRM/PivotReport/DAO/PivotReportCache.php
CRM/PivotReport/Upgrader.php
api/v3/PivotReport.php
sql/civicrm_pivotreportcache_source_comment.sql
sql/delete_cron_job_status_entry.sql
xml/schema/CRM/PivotReport/PivotReportCache.xml

- Renaming 'rebuildcachecronjob' to 'rebuildcachechunk' API action (and all related code occurences).
- Removing 'rebuildcache' cron job.
- Adding 'rebuildcachechunk' cron job (running hourly).

HW-433: Scheduled job issues

---

js/PivotReport.Export.js

- Adding Aggregator column containing Aggregator values.
- Adding Totals row to the exported table.
Pivot Report table used to test the export:
CSV export before fixing Totals:
CSV export after fixing Totals:

GS-104: CSV / TSV export file is not correct

---

js/PivotReport.Export.js

There were two issues with Pivot Report exporting:
1. Exported data didn't exclude filtered out values.
2. Data headers and totals were incorrect for more complex Pivot Table structure (when using both axes for Pivot Table).
Sample Pivot Table:
Incorrect export (before fixing) - see header and "total" row:
Correct export (after fixing) :

GS-104: Refactoring PivotReport.Export class

---

CRM/PivotData/AbstractData.php

Adding validation for Custom Field's value of File type.
This prevents from getting a warning message if 'file' Custom Field does not contain an expected data array.

HW-433: Validating 'file' Custom Field

---

CRM/PivotData/DataCase.php
CRM/PivotData/DataProspect.php

Adding 'Case Subject' field into Case and Prospect Pivot Reports.

GS-112: Subject field missing from Case and Prospect reports

---

CRM/PivotData/DataActivity.php
CRM/PivotData/DataCase.php
CRM/PivotData/DataContribution.php
CRM/PivotData/DataMembership.php

Reverts compucorp/uk.co.compucorp.civicrm.pivotreport#108
Revert PR based on comments on PR 108

Revert "Entities Missing From Reports"

---

js/PivotReport.PivotTable.js
templates/CRM/PivotReport/Page/PeopleReport.tpl

This PR adds a date filter to the admin's people report. This date filter will only include staff that have a valid contract and role for the given date.
For both the contract and roles, the start date must always be defined. If the end date is not defined for one of them, it means they are valid for any given date between the start date and the future.
No filter and all staffs are displayed even if they don't have a contract.
| Staff | From | To |
|----|----|----|
| Role | 2016-01-01 | --- |
| Contract | 2016-01-14 | --- |
| Manager | From | To |
|----|----|----|
| Role | 2018-01-01 | 2018-04-30 |
| Contract | 2018-01-01 | --- |
The people report template was modified and a record filter form was added which includes the head count date filter:
```html
<div …
```

PCHR-3504: Add people report filter

---

.github/workflows/release-pr.yml

Added Github Action to automate release PR creation.

CPS-464: Add github action to automate release pr

---

CRM/PivotData/AbstractData.php

This pr fixes an issue which restricted the user to generate pivot reports. The issue was caused by using a removed old function from civicrm core.

COMCL-835: Fix Pivot Report Generation

---

CRM/PivotReport/Upgrader.php
info.xml

This PR bumps the version and disables the Pivot Report Cache Build job for anyone who upgrades to this version of extension.

COMCL-1168: Bump Version And Disable Pivot Report Job
