compucorp/uk.co.compucorp.civicrm.pivotreport

CRM/Activityreport/Page/ActivityReport.php
CRM/Activityreport/Upgrader.php
CRM/PivotCache/AbstractGroup.php
templates/CRM/Activityreport/Page/ActivityReport.tpl

The system should automatically create and rebuild cache for all reports.
Although there was an API call that can be used to rebuild the report's cache, there was no way for users to use it.
1. A scheduled job was created to run daily, rebuilding the cache.
1. A button was added to the report's form so the user can rebuild the cache manually
1. A warning message was implemented to inform the user when the report's cache is not built

GS-57: Scheduled Job to Rebuild Cache 

---

CRM/Activityreport/Page/ActivityReport.php
CRM/Activityreport/Page/ContributionReport.php
CRM/Activityreport/Page/MembershipReport.php
CRM/Activityreport/Upgrader.php
CRM/PivotCache/AbstractGroup.php
CRM/PivotReport/AbstractData.php
api/v3/ActivityReport.php
templates/CRM/Activityreport/Page/ActivityReport.tpl
templates/CRM/Activityreport/Page/ContributionReport.tpl
templates/CRM/Activityreport/Page/MembershipReport.tpl
templates/CRM/Activityreport/Page/ReportSelector.tpl

The system should automatically create and rebuild cache for reports of all entities.
Although there was an API call that can be used to rebuild the report's cache, there was no way for users to use it. Job and button to rebuild cache were created based on develop branch and merged on PR #29, but it only works for activities. This needs to be applied to all entities.
Scheduled job and form button to rebuild cache works for all report entities.
1. A scheduled job was created to run daily, rebuilding the cache.
1. A button was added to the report's form so the user can rebuild the cache manually
1. A warning message was implemented to inform the user when the report's cache is not built

GS-57: Cache Rebuilding for All Entities

---

CRM/PivotReport/AbstractData.php
CRM/PivotReport/DataActivity.php
CRM/PivotReport/DataContribution.php
CRM/PivotReport/DataMembership.php
js/PivotReport.PivotTable.js
templates/CRM/Activityreport/Page/ActivityReport.tpl
templates/CRM/Activityreport/Page/ContributionReport.tpl
templates/CRM/Activityreport/Page/MembershipReport.tpl

All date type fields on the pivot table should have a derived field added grouping values by year-month. 
Only activity start date had the field, grouped by year-month. Other reports had derived fields grouped only by month and by year separately.
Added this functionality so the field is added to the report automatically for every field of date type. Removed previous derived fields used on Contribution and Memberships reports that were built using only the month and only the year.

GS-55: Add Date Fields Grouped by Month

---

CRM/Activityreport/Entity.php
CRM/PivotCache/GroupProspect.php
CRM/PivotReport/AbstractData.php
CRM/PivotReport/DataProspect.php
templates/CRM/Activityreport/Page/ProspectReport.tpl
templates/CRM/Activityreport/Page/ReportSelector.tpl
xml/Menu/activityreport.xml

- Implementing Prospect extension's support (if the extension is installed and enabled).
- Adding Prospect data into caching.
Sample Prospect report view:
Prospect report fields are susceptible to word replacement (during cache building).

GS-54: Prospect support

---

css/style.css
js/PivotReport.PivotTable.js
templates/CRM/Activityreport/Page/ActivityReport.tpl

The original idea was to remove the extra activity date filters on the page, as it is now possible to use 'from' and 'to' filters on each date field. However, the activities' main filter was conceived to limit the number of records loaded from the back-end into the pivot report, which is something that would be difficult to implement, and awkward UX-wise to use within in-field date filters. Thus, now the date filter only appears if the number of activities exceeds 50K.
The Dates filter appearing before the pivot table report appeared to be redundant, as you could also use the filters within date fields to filter results.
The dates field only appears if there are more than 50,000 activites in the database, explicitly explaining the use of this filter is to change the dataset used to build …

GS-68:  Remove Activity Date Filter

---

js/PivotReport.Dates.js
js/PivotReport.PivotTable.js

Relative dates filter was not working as expected. This should work as per relative dates filter in Find Activities. (ie; only when you select 'choose date range' option the date widget should show up).
Controls to select dates were visible even if a relative date was selected.
Controls disappear when a relative date is selected.

GS-71: Make Date Selection Widgets Disappear on Relative Dates

---

CRM/PivotReport/DataCase.php
CRM/PivotReport/DataProspect.php

- Updating DataProspect class to include unconverted Cases.
- Extending DataProspect class with DataCase class.
Prospect Pivot Report (includes unconverted case at the bottom)

GS-73: Include unconverted prospect in prospect report

---

js/PivotReport.PivotTable.js

Several problems were found when testing the relative date control on the pivot report. On one hand, when options like 'today' or 'this week' were selected, the filtering did not happen and there were no results. On the other, when a date range is set, the record list should only show those which are within the date range. Currently, it ticks the ones which are within the date range, but the other dates outside the range are still shown. It should only tick and show the ones within the date range.
Filtering of some relative dates was failing because hours of start and end were not being taken into account. Thus, for fields that were of both date and time, filters failed, as the time taken for both start and end dates was 00:00.
On the other hand, the specification of the relative dates …

GS-71: Fix Issues With Relative Dates Filters

---

CRM/PivotData/AbstractData.php
CRM/PivotData/DataContribution.php
CRM/PivotData/DataMembership.php

There was an issue causing Contact's ID and entity ID have the same values. It was because ID of Contact subchain was rewriting an entity ID (due to having the same field name). To handle this I changed Data classes for Contribution and Membership entities. Now the main entity's response and the subchain response is separated into different group so there is no field name conflict anymore.

GS-79: Contact id and id both show the contact id in memberships and contributions

---

packages/pivottable-cc/export_renderers.js

There was a bug in export_renderers.js script (referencing undefined index variable) which only appear when rendering TSV / CSV export with one or more columns.
Before fixing:
After fixing:

GS-81: CSV and TSV reports issue

---

CRM/PivotData/AbstractData.php
CRM/PivotData/DataCase.php
CRM/PivotData/DataProspect.php
js/PivotReport.PivotTable.js

Deleted entity data should not be listed in the report. This was not happening for Case and prospects entities.
Deleted cases were included in the pivot report. Also, cache rebuilding process was failing with fatal error, as client_id was not being resolved correctly to the contact_id, since for the field client_id to be returned, contact_id must be part of return fields.
Deleted cases are no longer in either Case or Prospect. Added contact_id to return fields. Changed 'IN' operator on chained API call to contact for '=' operator, since 'IN' is unsupported for CiviCRM version <= v4.7.18.

GS-76: Exclude Deleted Cases From Report

---

js/PivotReport.PivotTable.js

When a date range is set, the record list should only show those which are within the date range. The first time when you filter, it works as expected, but once you click apply and then go back to the filter the other dates outside the range are still shown.
The apply button was resetting the state of values, as this is the behaviour implemented by the pivot table jquery extension.
The default jquery behaviour was overridden by refiltering the dates when clicking on the 'Apply' and 'Cancel' buttons.

GS-71: Fix Resetting of Inner Dates Filter

---

CRM/PivotData/AbstractData.php

Rebuilding report caches through the front end caused a large amount of PHP notices to be logged to watchdog, affecting negatively the performance of the process.
```
INSERT INTO watchdog (uid, type, message, variables, severity, link, location, referer, hostname, timestamp) VALUES ('1', 'php', '%type: !message in %function (line %line of %file).', 'a:6:
{s:5:\"%type\";s:6:\"Notice\";s:8:\"!message\";s:32:\"Undefined index: Activity Status\";s:9:\"%function\";s:42:\"CRM_PivotData_AbstractData->formatResult()\";s:5:\"%file\";s:144:\"/var/www/greenhouse-data.ccuptest.co.uk/httpdocs/sites/all/civicrm_extensions/uk.co.compucorp.civicrm.pivotreport/CRM/PivotData/AbstractData.php\";s:5:\"%line\";i:531;s:14:\"severity_level\";i:5;}
', '5', '', …
```

GS-83: Fix Source of Multiple PHP Notices on Cache Rebuild

---

CRM/PivotData/DataCase.php

"Case Client Display Name" always shows up the same contact in the case and prospect reports, for all cases/prospects. Also, it should show all case clients when there are multiple case clients.
CiviCase can be configured to have more than one client per case, but the pivot report was only showing data for the first client found.
Processed all client data into the report by concatenating and deduping each field's values.

GS-86: Handle Cases With Multiple Clients

---

CRM/PivotData/DataCase.php
CRM/PivotData/DataProspect.php

Multiple case clients were showing up on Cases Report, but client subtypes were not. 
Also, all this (multiple case clients, case client subtype) should work in Prospect reports as well.
A contact can have many subtypes, which is why they weren't being shown, as
the result was an array and was being used as a string.
Implemented treatment of array values for clients by imploding into a comma
separated string.

GS-86: Fix Subtypes on Cases and Prospect Reports

---

CRM/PivotData/AbstractData.php
CRM/PivotData/DataActivity.php

Text fields included on the pivot report have the potential to break the exported CSV ot TSV formats, if they contain special characters like '\n', commas, or tabs.
If text fields contained characters used on TSV/CSV exports to format the output, the export would break.
Fixed problem by filtering out '\r' and '\n' characters and embedding text fields within double quotations, so other characters like commas or tabs don't alter the report.

GS-66: Prevent Breaking of Exports Due to Special Charactes

---

css/style.css
js/PivotReport.PivotTable.js
templates/CRM/PivotReport/Page/ReportConfig.tpl

The requirement was to replace the current CSV and TSV Export options available on the Chart Type selection box for two distinct buttons, that should appear to the right this combo box.
In order to generate a CSV or TSV export, you had to change the Chart Type to one of the two and then click on the link appearing at the middle of the pivot report to actually download the fie.
Added buttons to the form, implementing file generation using the same export renderers being used by existing pivot report. Also removed CSV and TSV export options from chart type select box.

GS-89: Implement CSV and TSV Export Buttons

---

CRM/PivotReport/Upgrader.php
pivotreport.php

New menu items for each entity pivot report should be added to the database, instead of using hooks to alter the menu. These items should be added on extension installation, activated when the extension is enabled, deactivated when the extension is disabled and deleted on uninstallation.
Items were being added to the menu using hooks, which required the caches to be deleted so the menu was rebuilt. There was no separator below Pivot Report menu item.
Menu items are added, enabled, disabled and deleted on extension installation, enabling, disabling and uninstallation, respectively. There is a separator below Pivot Report menu item.

 GS-88: Add Menu Items to Navigation DB Table Instead of Using Hooks

---

CRM/PivotData/AbstractData.php
CRM/PivotReport/Entity.php

On HW local site there was an error during caching Contribution entity. It was caused because CiviContribute component was disabled on the site. To fix this issue I've extended entities validation to check for API response on required entities.
Now we can define 'extensions' and 'entities' array values as requirements for any supported entity in CRM_PivotReport_Entity class. It allows to check these requirements before adding the entity to supported entities list.
For example:
$entities = array(
'Prospect' => array(
'**extensions**' => array(
'uk.co.compucorp.civicrm.prospect',
),
'**entities**' => array(
'Contribution',
'Pledge',
),
);
Additionally, each entity is validated with API call to the entity itself (even if we don't specify required entities).
For example:
$entities = array( …

GS-43: Supported entities validation

---

CRM/PivotData/AbstractData.php
CRM/PivotData/DataCase.php

There was an issue that multivalues custom fields were shown inline instead of splitting them into separated rows (which is the main idea of pivot data). It was caused by a bug in formatRow() method (used for each entity except Activity which has it's own recursive implementation of this method).
Before:
After fixing:

GS-92: Multiselect fields error in pivot table

---

js/PivotReport.PivotTable.js

There was a performance issue using UI date filters on Pivot Table date fields. It was caused mostly by triggering 'click' event on each date filter checkbox. Fortunatelly we can achieve the same by modifying some properties and classes for the checkboxes which is a lot faster. For me previously selecting/deselecting all dates for 6k activities took 29 seconds, now it's under 1 second.
Also I've updated filterDateValues with additional parameter allowing to use the method with 'Apply' / 'Cancel' actions and not modify the checkboxes state so it's possible to select/unselect particular date checkboxes along with using date range filters. Previously particular date checkboxes were ignored if we already defined date range values.
Before (shows only the second issue because the first one took …

GS-99: Stress tests

---

CRM/PivotData/DataActivity.php

- Excluding text/textarea custom fields from Activity Pivot Report cache building.
- Changing multivalues generated at once limit to 500 for Activity entity.

HW-432: Pivot Report caching building improvement

---

CRM/PivotReport/Upgrader.php
css/style.css
css/style_admin.css
js/PivotReport.Admin.js
js/PivotReport.Preloader.js
templates/CRM/PivotReport/Page/PivotReportAdmin.tpl
templates/CRM/PivotReport/Page/ReportPreloader.tpl

- Renaming menu item from "Pivot Report Config" to "Pivot Report Configuration".
- Adding in-progress info with spinner icon.
- Modifying progress bar (also for data loading)
- Disabling "Refresh All Pivot Reports" button when cache rebuilding is in progress.

GS-91: Pivot Config ux changes

---

CRM/PivotCache/AbstractGroup.php
CRM/PivotCache/GroupActivity.php
CRM/PivotCache/GroupCase.php
CRM/PivotCache/GroupContribution.php
CRM/PivotCache/GroupMembership.php
CRM/PivotCache/GroupProspect.php
CRM/PivotData/AbstractData.php
CRM/PivotData/DataCase.php
CRM/PivotData/DataContribution.php
CRM/PivotData/DataInterface.php
CRM/PivotData/DataMembership.php
api/v3/PivotReport.php
js/PivotReport.Admin.js
js/PivotReport.PivotTable.js
templates/CRM/PivotReport/Page/ActivityReport.tpl
templates/CRM/PivotReport/Page/CaseReport.tpl
templates/CRM/PivotReport/Page/ContributionReport.tpl
templates/CRM/PivotReport/Page/MembershipReport.tpl
templates/CRM/PivotReport/Page/ProspectReport.tpl

There was an issue with progress bar loading cached data on some sites. It was causing by different number of cached data rows comparing to actual Entity rows (because of multivalues rows extending the total number of cached data).
Fixing it required to store total cached rows number into cache and then use them instead of requesting particular entity's for 'getcount' API action. Also it's more proper to store cached number of records and rely on them instead of API's 'getcount' response because the number of entities records may change in time comparing to the cached records.
Also I've added unique ID columns to SQL when retrieving cached data (not defining it might cause to return the data with random order).
I've also removed cache rebuilding functionality from Pivot Table page UI …

HW-433: Progress bar issue

---

CRM/PivotCache/AbstractGroup.php
CRM/PivotCache/PivotReportCronJobStatus.php
CRM/PivotData/AbstractData.php
CRM/PivotData/DataInterface.php
CRM/PivotReport/BAO/PivotReportCache.php
CRM/PivotReport/DAO/PivotReportCache.php
CRM/PivotReport/Upgrader.php
api/v3/PivotReport.php
sql/civicrm_pivotreportcache_is_active.sql
xml/schema/CRM/PivotReport/PivotReportCache.xml

This PR adds new 'rebuildcachecronjob' API action for PivotReport entity.
It doesn't require any parameters (it automatically walks through available Pivot Report entities and caches further data on each run). It uses 'lock' property so there is no overlapping when running the action before previous run is finished.
Caching is stored as 'non-active' until whole cache is built. Then the cache is marked as 'active' and is used by Pivot Reports. This way we can build the cache without harming the existing one and use Pivot Reports with previously built cache without waiting until current build process is complete.
The action can be add into CiviCRM scheduled jobs to run repeatedly. Each run caches one chunk of Pivot Report data and saves information (such as offset, index, page) needed for …

HW-433: Pivot Report rebuild cache with cron job

---

CRM/PivotData/AbstractData.php

Setting Option Value as field value if Option Label is not available (in case that some Options are removed from Option Group).

HW-433: Setting Option Value as field value if Option Label is not available

---

CRM/PivotCache/AbstractGroup.php
CRM/PivotCache/GroupActivity.php
CRM/PivotCache/GroupCase.php
CRM/PivotCache/GroupContribution.php
CRM/PivotCache/GroupMembership.php
CRM/PivotCache/GroupProspect.php
CRM/PivotData/AbstractData.php
CRM/PivotData/DataInterface.php
CRM/PivotReport/BAO/PivotReportCache.php
CRM/PivotReport/DAO/PivotReportCache.php
CRM/PivotReport/Entity.php
CRM/PivotReport/Upgrader.php
api/v3/PivotReport.php
sql/civicrm_pivotreportcache_source.sql
xml/schema/CRM/PivotReport/PivotReportCache.xml

Adding 'source' field into Pivot Report cache to distinguish three different actions of cache rebuilding (single action rebuilding whole cache, cron job action rebuilding cache chunk, UI action). This allows to separate inactive cache (by its source) and preserves from wiping partially built cache by other cache build action with different source.

HW-433: Implementing cache source field

---

CRM/PivotReport/Upgrader.php
pivotreport.php

Some users are not able to view pivot reports. It looks as though unless a user has the 'Administer CiviCRM' permission ticked in addition to 'access CiviCRM pivot table reports' permission, they aren't able to view preconfigured reports.
Users without 'Administer CiviCRM' permission were unable to access pivot reports. There were also problems using the API calls needed to build the reports, as they also required 'Administer CiviCRM' permission.
Fixed by making the 'Reports' menu item accessible by users with the 'access CiviCRM pivot table reports' permission and by using the alterAPIPermissions hook to enable required API end-points.

GS-121: Fix Pivot Report Access Permissions

---

CRM/PivotCache/AbstractGroup.php
CRM/PivotData/DataActivity.php
CRM/PivotData/DataCase.php
CRM/PivotData/DataContribution.php
CRM/PivotData/DataMembership.php

In a site with a lot of cases, a good number of them were missing on the pivot reports.
On looking into the code, when entities are cached, the path column (unique path name for cache element) is not unique in few cases. The main part of this 'path' is $index which is usually the a 'date' like ('start date' for cases, 'date received' for contributions etc). So I guess if a number of cases are added with same start date for example, they are overwritten in cache table and so missing from reports.
Adding entity ID as part of 'path' to make it unique fixes the issue

Entities Missing From Reports

---

CRM/PivotData/AbstractData.php

In a site with a lot of cases, a good number of them were missing on the pivot reports.
On looking into the code, getPaginatedResults() checks for previous index name and if its the same it increments the page number and if the index is different it resets page number to 0. However in certain cases there are indexes which are not sequential but have the same index name. In such cases the page number is wrongly set to 0 and the old page entities are missed.
Maintain an array of index names and page numbers instead of a single index name.

GS-123: Fix getPaginatedResults Page Number Logic

---

.gitignore
CRM/PivotData/AbstractData.php
CRM/PivotData/DataActivity.php
CRM/PivotData/DataCase.php
CRM/PivotData/DataContribution.php
CRM/PivotData/DataMembership.php
CRM/PivotData/DataProspect.php

GS have requested that we add four additional fields to the prospect pivot report, and that we re-name a couple of others. This poses the problem of doing this changes specific to Greenhouse Sport's installation, 
- "Prospect client type" should become "Contact Type"
- "Prospect client subtype" should become 'Org Type"
- Supplier Sub-Type
- Donor Sub-Type
- Education Sub-Type
- Gov Sub-Type
There was no way to add custom fields per installation to prospect report, nor a way to customize field labels used on the pivot report.
Implemented the possibility to add a json configuration file per Data entity (Activity, Membership, Case, Contribution, Prospect) to modify its behaviour, by configuring field label mappings to alter field labels and to add specific client custom fields to prospects …

GS-130: Add Specific Custom Fields to Prospects Report and Customize Labels

---

CRM/PivotData/DataContribution.php

This pr removes the is_current_revision parameter from the contribution count api call to remove the discrepancies between count api and data api calls for contribution.While sending the api call for fetching the contribution count we are attaching an extra parameter by the name of is_current_revision as can be seen [here](https://github.com/compucorp/uk.co.compucorp.civicrm.pivotreport/blob/master/CRM/PivotData/DataContribution.php#L174) but while fetching the actual data the same parameter was not being sent as can be seen [here](https://github.com/compucorp/uk.co.compucorp.civicrm.pivotreport/blob/master/CRM/PivotData/DataContribution.php#L19-L21) This led to different data in both the apis.
The count of data was not getting effected even after new records were being inserted.
Removal …

CPS-342: Remove is_current_revision parameter from count api

---

CRM/PivotReport/Upgrader/Base.php
pivotreport.civix.php
pivotreport.php

This PR fixes is to updates civix file and an upgrader base class.  The base class and civix file are generated automatically by running `civix generate:upgrader
`
The reason for regenerating the civix file and base upgrader class because CiviCRM changed the way they handle warning for using a deprecated function.  See this [PR ](https://github.com/civicrm/civicrm-core/pull/19256).
The changed will always throw use deprecated warning if the deprecated function is used in anywhere, for example, Drupal module, CiviCRM extension. This would not have an issue we install the extension / module via user interface. However, when we use Drush site-install command to install the Drupal site that ship with a Drupal profile that install the extension when creating a site. 
Any module or extension …

COMCL-101: Regenerate civix file and Base upgrader class

---

CRM/PivotCache/AbstractGroup.php
CRM/PivotCache/GroupActivity.php
CRM/PivotData/AbstractData.php
CRM/PivotData/DataProspect.php

There are some issues with missing entities data in the pivot report. For example in the prospect pivot report for a client, some prospects that were present were missing in the prospect pivot report. The previous temporary fix for this was to increase the value of the [ROWS_API_LIMIT](https://github.com/compucorp/uk.co.compucorp.civicrm.pivotreport/blob/master/CRM/PivotData/AbstractData.php#L14) constant which seems to fix this issue. This PR properly fixes this issue.
There were missing entities data in the pivot report for an entity.
The issue with missing entities data in the pivot report for an entity is fixed.
The pivot report extension has business logic that expects the index for an entity (Usually the start data) to be ordered either in ascending or descending order, …

GSSPRT-100: Fix Issue With Missing Entities Data

---

pivotreport.php

When the Pivot extension is installed on a fresh site, the schema version for the extension is NULL in the `civicrm_extension` table even though the extension has upgraders and the schema version is supposed to be set to the latest upgrader number, in this case it should have been `0012`. This causes an issue on the extensions page, where a notice is shown that there are pending updates for pivot report extension.
The issue describe above exists
We recently updated the civicrm base upgrader and civix classes in this PR: https://github.com/compucorp/uk.co.compucorp.civicrm.pivotreport/pull/124. Initially, before the upgrade, the function responsible for setting the current revision for the extension was invoked on the onInstall function, see: …

PS-527: Fix issue with NULL schema version upon install

---

CRM/PivotReport/BAO/PivotReportConfig.php

When a new pivot report is saved, the newly saved report does not show up in the dropdown list.
The issue was because the API call for fetching the list of saved pivot report configs was fetching 25 configs by default. The fix was to set the call to fetch configs without a limit.

GSSPRT-124: Fix Issue With Saved Reports Not Displaying in The Report List

---

CRM/PivotData/AbstractData.php

This PR solved the error presented on Activity reports, which made the page keep loading indefinitely. 
On Reports > Pivot Report > Activity, the progress bar keep loading without end, with numbers greater than the 100%
The page finishes loading correctly.
The fix consists of not overriding the `$page` variable that is being passed on the `getPaginatedResults` method. This variable keeps track of the last page used for a giving index, when called in `rebuildData` method, on the same class.
It should be reset to 0 only when the index change.

FEMSSPRT-44: Fix Activity Report Problem on Loading

---

CRM/PivotData/DataProspect.php

This PR solves an issue related to Prospect reports, that occurred when one or more prospects had no contact associated.
All the prospects without contact were presented in one row:
In this screenshot, we can see the prospect with IDs 2790 and 2791 mixed in the same row, with 25 random contacts appearing on the contact column. There are 25  because of the default limit on the API call.
The prospects without contacts are not displayed.
This chained API call inside the Prospect.get is causing the problem:
```php
'api.Contact.get' => array('id' => '$value.client_id', 'return' => array('id', 'contact_type', 'contact_sub_type', 'display_name')),
```
because `$value.client_id` is null on the Case data.
For solving this, we should filter by Cases having client:
```php
'client_id' => ['IS NOT …
```

GSSPRT-137: Filter Prospects Without Client

---

CRM/PivotData/DataProspect.php

This PR solves a problem generating the cache for the prospect reports. The process of cache generation was stuck on a percentage less than 100%.
While running the "Refresh All Pivot Reports", the action get stopped, because of a timeout error in one of the Ajax request performed:
The action finishes without errors:
The timeout observed is in one of the requests to the Prospect API (with Js library), for getting a set of results in order to create the report cache.
For solving this, without having to think about query optimization, we can use the constant defined on `CRM_PivotData_AbstractData` class named `ROWS_API_LIMIT`. This indicates the number of results to be queried on every call to CiviCRM API, for each entity. A lower number could speedup the query time, and the result will be …

GSSPRT-148: Decrease the rows returned for Prospect report cache

---

pivotreport.php

CiviCRM 5.0+ uses a newer format for declaring permissions.  As of Civi 5.71, the old format is deprecated.  This should close #141.

permission fix for CiviCRM 5.71+
